### ISSUE TITLE
nazwy plików graficznych

### ISSUE THREAD

**Issue by 84lukaszkaminski** [infoshareacademy/jfdzw1-valor#4]
https://github.com/infoshareacademy/jfdzw1-valor/blob/2b395ddf5afefad454af4f537c569da980f8669e/index.html#L16

dobrze jest nadać taką nazwę plikom graficznym, aby bezpośrednio odnosiły się do zawartości pliku, np. zamiast logo.png - valor-logo.png. wiąże się to z pozycjonowaniem, np [pozycjonowanie-grafik-w-google](https://www.netim.pl/pozycjonowanie-grafik-w-google/)

**Comment by palkak** [comment]
Poprawione
