### ISSUE TITLE
pusty alt

### ISSUE THREAD

**Issue by 84lukaszkaminski** [infoshareacademy/jfdzw1-valor#5]
https://github.com/infoshareacademy/jfdzw1-valor/blob/76778d0e67221c6375bfb0b46543a579ac49c19e/index.html#L16

dla każdej grafiki na stronie warto dać atrybut alt (a już szczególnie nie zostawiamy pustego atrybutu; co on oznacza? ma zostać puste - takie zamierzenie, i nie dotykać!? kiedyś będzie?)
[o atrybucie alt](http://html.com/attributes/img-alt/)

**Comment by palkak** [comment]
Poprawione
